global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "cloudflare-exporter"
    static_configs:
      - targets: ["host.docker.internal:8787"]
    metrics_path: /metrics
    scrape_timeout: 30s
